name: Build and Test Maven Spring Boot App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          maven-version: '3.8.4' # Aquí puedes especificar la versión de Maven que desees

      - name: Build and Test
        run: |
          chmod +x mvnw
          ./mvnw clean install
