name: Build and Test Maven Spring Boot App

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Download Maven 3.6.3
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar xzvf apache-maven-3.9.1-bin.tar.gz
          export PATH=$PWD/apache-maven-3.9.1/bin:$PATH

      - name: Build and Test
        run: |
          chmod +x mvnw
          ./mvnw clean install
