name: Compilar y ejecutar test para mi APIREST con Spring Boot y Maven

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          maven-version: '3.9.1'

      - name: Build and Test
        run: |
          chmod +x mvnw
          ./mvnw clean install
